# Generated by Django 3.0.7 on 2020-06-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('defaut', models.CharField(choices=[('T', 'Tyrannique'), ('F', 'Faible'), ('M', 'Médiocre'), ('D', 'Dominé (par sa femme, son conseiller)')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('statut', models.TextField(choices=[('V', 'Vieille famille'), ('N', 'Nouvelle famille')], max_length=1)),
                ('ambiance', models.TextField(choices=[('I', 'Intrigues, jalousies, rivalités'), ('L', 'Lourd secret/passé'), ('D', 'Désespoir, fin de règne'), ('T', 'Tristesse, drame récent'), ('A', 'Autoritaire, chef de famille très fort'), ('F', 'Faible, chef de famille sans autorité, anarchie'), ('P', "Parasite : un conseiller extérieur jouit d'une influence trop importante")], max_length=1)),
                ('secret', models.TextField(blank=True)),
                ('richesses', models.CharField(choices=[('F', 'Faibles'), ('M', 'Moyennes'), ('E', 'Elevées')], max_length=1)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.Personne')),
            ],
        ),
    ]
