# Generated by Django 2.0 on 2020-04-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='jdr.Categorie'),
        ),
    ]
